spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: select 1 from dual
      validation-query-timeout: 30
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      filters: stat, wall, log4j #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: jackson
  application:
    name: dbproxy

jasypt:
  encryptor:
    password: yylc8888

management:
  server:
    port: 21007
  trace:
    http:
      include: REQUEST_HEADERS,RESPONSE_HEADERS,COOKIE_HEADERS,AUTHORIZATION_HEADER,PRINCIPAL,REMOTE_ADDRESS,SESSION_ID,TIME_TAKEN
  endpoint:
    shutdown:
      enabled: true
    jolokia:
      config:
        debug: true
      enabled: true
    health:
      show-details: when_authorized
  endpoints:
    web:
      base-path: /dbproxy-1
      exposure:
        include: "metrics,threads,beans,health,env,info,logfile,loggers,threaddump,jolokia,scheduledtasks,httptrace,mappings"
logging:
  file: ${user.dir}/logs/app-error.log
server:
  port: 11007
  servlet:
    session:
      cookie:
        max-age: 3600s
    context-path: /dbproxy

