spring:
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      client:
        enabled: false

database:
  druid:
    configs:
      - database: db1
        driverClass: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.10.5.53:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: 123456
      - database: db2
        driverClass: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.100.9.85:3306/springboot?useUnicode=true&characterEncoding=utf-8
        username: root
        password: "@WSX1qaz"