spring:
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: jackson
  application:
    name: dbproxy

management:
  server:
    port: 21007
  trace:
    http:
      include: REQUEST_HEADERS,RESPONSE_HEADERS,COOKIE_HEADERS,AUTHORIZATION_HEADER,PRINCIPAL,REMOTE_ADDRESS,SESSION_ID,TIME_TAKEN
  endpoint:
    shutdown:
      enabled: true
    jolokia:
      config:
        debug: true
      enabled: true
    health:
      show-details: when_authorized
  endpoints:
    web:
      base-path: /dbproxy-1
      exposure:
        include: "metrics,threads,beans,health,env,info,logfile,loggers,threaddump,jolokia,scheduledtasks,httptrace,mappings"
logging:
  file: ${user.dir}/logs/app-error.log
server:
  port: 11007
  servlet:
    session:
      cookie:
        max-age: 3600s
    context-path: /dbproxy

