spring:
  datasource:
    url: jdbc:mysql://10.10.5.175:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      client:
        enabled: false
server:
  port: 11007