spring:
  datasource:
    url: jdbc:mysql://192.168.19.81:3306/ynrpt?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: ENC(X0KblZwVictx8TKvS0NIb9r7RX4BOGqF)
  security:
    user:
      name: sadmin
      password: 38741cb511c43e8d2c
  boot:
    admin:
      client:
        url: http://monitor.okcoming.top
        username: sadmin
        password: YY123456
        instance:
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
          service-url: http://dashboard.okcoming.top${management.endpoints.web.base-path}
          management-url: http://dashboard.okcoming.top${management.endpoints.web.base-path}/actuator
          health-url: http://dashboard.okcoming.top${management.endpoints.web.base-path}/actuator/health
